language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: qGPHZaRbKb2mDY8hS6gbJyOHuNvXPaA+/getNPAUhY6lho+VL4pb0aAk6I2K71DLz0OzBP9LRLf7uUQVnoV76+bw2tLPe0RVDpmPCxSOHi929Z3qJr9AVFBLHn0JTw2/As2w0ntLL37YkdKxzPPsieurUtSuMFOFzDEjSYOulhR6jAM3UvZLnea32rRYm1IJelUEuSa7FfIGHBWO9BiyqS5OOHRCIyTfsSWZXea6ZcCmDJim4+ZX1xdru9yp5rAs6CmFWHGAVnco4xRuYWsRPV6C0Jn7p7Ryk8Dd6APWjXqDWqaLXBoNE2gSUxOjloRpChSawl3Yw5h7hZZk96OyyZz2sFA5B9jT+OWbKEHMZSFmP7qCYUJ/6vrR0loDjx2Q4frc86VBs6BDC/Slk3mankA679oiwFXdoWTUV4x+rqeBkDYqz5kj0J+kz+QosCANvl/NHBv7/9GA1x4vc3vBO1UTowDelwcjKtpdId7higtqkQKhgKCf7OIpkgYZSCy5VEb4rvqyT9rWdKTbjGuYf5rD2TIxHXFbC0i7kWpo6F33OXyVqHQY5l9mj0pooW/CcXUjhQeXlt8PYsxPwTM40FR8Cl2VUe9ukpDIoIUH4gNYz7D0yr7yPcLIEh9qOgY5FZsgeqNZC3eL942wJwTTBKnVPNVlhjt/fnFFNY9XGvo=
  app: quiet-dawn-76362
  on:
    repo: sanadler/mytube-server
